### ISSUE TITLE
Check Support for Calibre 5

### ISSUE THREAD

**Issue by fallaciousreasoning** [fallaciousreasoning/CalibreLibgenStore#4]
Calibre 5 migrated from Python 2.7 to Python 3. I'm unsure whether this plugin still works.

**Comment by harmtemolder** [comment]
Checking it now, will update when needed

**Comment by harmtemolder** [comment]
I upgraded everything needed for Python 3 (and did some code cleanup). @fallaciousreasoning Could you test [v0.4](https://github.com/fallaciousreasoning/CalibreLibgenStore/releases/tag/v0.4)?

**Comment by fallaciousreasoning** [comment]
Awesome nice work! It all seems to be working :)
